language:   rust
rust:       nightly
sudo:       false
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
script:     .travis/build.sh
