language:   rust
rust:       nightly
sudo:       true
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc-arm-none-eabi
before_script:
    - sudo apt-get install libnewlib-arm-none-eabi
script:
    - .travis/build.sh
